# Generated by Django 4.2.4 on 2023-08-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_imagen_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagen_Archivo',
        ),
        migrations.AddField(
            model_name='viaje_general',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='viaje_general',
            name='image_data',
            field=models.BinaryField(null=True),
        ),
    ]
