# Generated by Django 4.2.4 on 2023-08-26 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_delete_imagen_archivo_viaje_general_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje_general',
            name='image',
        ),
        migrations.RemoveField(
            model_name='viaje_general',
            name='image_data',
        ),
    ]
