# Generated by Django 4.2.4 on 2023-08-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_remove_viaje_general_fechafinalizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('actividades', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='viaje_dia',
            name='actividades',
        ),
        migrations.RemoveField(
            model_name='viaje_dia',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='viaje_general',
            name='image',
        ),
        migrations.RemoveField(
            model_name='viaje_general',
            name='image_data',
        ),
        migrations.AddField(
            model_name='viaje_general',
            name='diasViaje',
            field=models.ManyToManyField(related_name='viaje', to='viajes.viaje_dia'),
        ),
        migrations.RemoveField(
            model_name='viaje_dia',
            name='destinos',
        ),
        migrations.AddField(
            model_name='viaje_dia',
            name='destinos',
            field=models.ManyToManyField(related_name='dias_viaje', to='viajes.destino'),
        ),
    ]
