# Generated by Django 4.2.4 on 2023-08-29 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viajes', '0007_destino_remove_viaje_dia_actividades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje_general',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
