# Generated by Django 4.2.4 on 2023-08-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0009_actividad_remove_destino_actividades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje_general',
            name='diasViaje',
            field=models.ManyToManyField(null=True, related_name='viaje', to='viajes.viaje_dia'),
        ),
    ]
