# Generated by Django 4.2.4 on 2023-09-05 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0010_alter_viaje_general_diasviaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje_Dia_Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='destino',
            name='actividades',
        ),
        migrations.RemoveField(
            model_name='viaje_general',
            name='diasViaje',
        ),
        migrations.AddField(
            model_name='destino',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='viaje_dia',
            name='viaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viaje_dia', to='viajes.viaje_general'),
        ),
        migrations.AddField(
            model_name='viaje_general',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='viaje_dia',
            name='destinos',
            field=models.ManyToManyField(related_name='destinos', to='viajes.destino'),
        ),
        migrations.AlterField(
            model_name='viaje_general',
            name='cantidadDias',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.AddField(
            model_name='viaje_dia_destino',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.destino'),
        ),
        migrations.AddField(
            model_name='viaje_dia_destino',
            name='dia_viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.viaje_dia'),
        ),
    ]
