# Generated by Django 4.2.4 on 2023-08-31 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0011_remove_destino_actividades_destino_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje_general',
            name='diasViaje',
        ),
        migrations.AddField(
            model_name='viaje_dia',
            name='viaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viaje', to='viajes.viaje_general'),
        ),
    ]
