# Generated by Django 4.2.4 on 2023-09-04 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0011_remove_destino_actividades_destino_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje_general',
            name='diasViaje',
        ),
        migrations.AddField(
            model_name='viaje_dia',
            name='viaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viaje_dia', to='viajes.viaje_general'),
        ),
        migrations.AddField(
            model_name='viaje_general',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='viaje_dia',
            name='destinos',
            field=models.ManyToManyField(related_name='destinos', to='viajes.destino'),
        ),
        migrations.AlterField(
            model_name='viaje_general',
            name='cantidadDias',
            field=models.IntegerField(null=True),
        ),
    ]
