# Generated by Django 4.2.4 on 2023-09-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0012_mes_viaje_general_mesdesde_viaje_general_meshasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje_general',
            name='calificacion',
            field=models.IntegerField(null=True),
        ),
    ]
