# Generated by Django 4.2.4 on 2023-08-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0012_remove_viaje_general_diasviaje_viaje_dia_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje_dia',
            name='destinos',
            field=models.ManyToManyField(related_name='destinos', to='viajes.destino'),
        ),
    ]
