# Generated by Django 4.2.4 on 2023-09-02 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0013_alter_viaje_dia_destinos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje_dia',
            name='viaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viaje_dia', to='viajes.viaje_general'),
        ),
        migrations.AlterField(
            model_name='viaje_general',
            name='cantidadDias',
            field=models.IntegerField(null=True),
        ),
    ]
