# Generated by Django 4.2.4 on 2023-09-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0013_alter_viaje_dia_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje_general',
            name='cantidadDias',
            field=models.IntegerField(null=True),
        ),
    ]
