# Generated by Django 4.2.4 on 2023-09-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0014_alter_viaje_general_cantidaddias'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje_general',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
