# Generated by Django 4.2.4 on 2023-09-03 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0014_alter_viaje_dia_viaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje_Dia_Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.destino')),
                ('dia_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.viaje_dia')),
            ],
        ),
    ]
