# Generated by Django 4.2.4 on 2023-09-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0014_remove_destino_descripcion_destino_latitud_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viaje_Dia_Destino',
        ),
    ]
