# Generated by Django 4.2.4 on 2023-09-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0015_delete_viaje_dia_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje_general',
            name='esPrivado',
            field=models.BooleanField(null=True),
        ),
    ]
