# Generated by Django 4.2.4 on 2023-09-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0016_viaje_general_mesdesde_viaje_general_meshasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje_general',
            name='mesDesde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viaje_general',
            name='mesHasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
