# Generated by Django 4.2.5 on 2023-10-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0016_viaje_general_esprivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje_general',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
