# Generated by Django 4.2.4 on 2023-10-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0017_viaje_general_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje_general',
            name='estado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
