# Generated by Django 4.2.4 on 2023-09-05 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0017_alter_viaje_general_mesdesde_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMes', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='viaje_general',
            name='mesDesde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_desde', to='viajes.mes'),
        ),
        migrations.AlterField(
            model_name='viaje_general',
            name='mesHasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_hasta', to='viajes.mes'),
        ),
    ]
