# Generated by Django 4.2.4 on 2023-09-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0018_mes_alter_viaje_general_mesdesde_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje_general',
            name='mesDesde',
        ),
        migrations.RemoveField(
            model_name='viaje_general',
            name='mesHasta',
        ),
    ]
