# Generated by Django 4.2.4 on 2023-10-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0019_remove_viaje_dia_destinos_viaje_dia_destinos'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='viajes')),
                ('viaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='viajes.viaje_general')),
            ],
        ),
    ]
