# Generated by Django 4.2.4 on 2023-09-05 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0019_remove_viaje_general_mesdesde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje_general',
            name='mesDesde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_desde', to='viajes.mes'),
        ),
        migrations.AddField(
            model_name='viaje_general',
            name='mesHasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_hasta', to='viajes.mes'),
        ),
    ]
