# Generated by Django 4.2.4 on 2023-10-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0020_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destino',
        ),
        migrations.AlterField(
            model_name='viaje_dia',
            name='destinos',
            field=models.JSONField(null=True, verbose_name='estino'),
        ),
    ]
