# Generated by Django 4.2.4 on 2023-10-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0021_delete_destino_alter_viaje_dia_destinos'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje_dia',
            name='imagen',
            field=models.ImageField(null=True, upload_to='viajes'),
        ),
        migrations.DeleteModel(
            name='imagen',
        ),
    ]
