# Generated by Django 4.2.4 on 2023-10-29 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viajes', '0022_viaje_dia_imagen_delete_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje_general',
            name='usuariosPermitidos',
            field=models.ManyToManyField(related_name='viajes', to=settings.AUTH_USER_MODEL),
        ),
    ]
