# Generated by Django 4.2.4 on 2023-08-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0002_alter_persona_altura_alter_persona_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nombre',
            new_name='nombreUsuario',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='edad',
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.CharField(default='ejemplomail@ejemplo.com', max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(default='1234', max_length=200),
        ),
    ]
