# Generated by Django 4.2.4 on 2023-08-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SitioWeb', '0003_rename_nombre_persona_nombreusuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
